# Assignment: Writing a Compose File

# Goal: Create a compose config for a local Drupal CMS website

#- Use the `drupal` image along with the `postgres` image
#- Set the version to 2
version: '2'

services:

  drupal:
    image: drupal
    ports: #- Use `ports` to expose Drupal on 8080
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'foo'
      #- Be sure to setup POSTGRES_PASSWORD on postgres image
      #
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:


# - Walk though Drupal config in browser at http://localhost:8080
# - Tip: Drupal assumes DB is localhost, but it will actually be on the compose service name you give it
# - Use Docker Hub documentation to figure out the right environment and volume settings
# - Extra Credit: Use volumes to store Drupal unique data
